apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    appName: nginx
    demoFor: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lb
  labels:
    appName: nginx
    demoFor: LoadBalancer
spec:
  containers:
  - name: nginx
    image: nginx:1.19
    ports:
    - containerPort: 80
