apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLkJGT3dvUHppYnVURmFWcWRnRmdWUkx1RA==
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-aks
spec:
  provider:
    vault:
      server: "http://vault-internal.cloudaws.shop:8200"
      path: "roboshop-dev"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth: # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-aks
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-aks
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: foobar
    remoteRef:
      key: foo
      property: my-value
