apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example-secret-store
    kind: SecretStore
  target:
    name: my-k8s-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: DB-PASSWORD 
  - secretKey: username
    remoteRef:
      key: DB-USERNAME 